[package]
name = "dunh"
version = "1.0.0"
edition = "2021"
description = "Highlights code for printing"
repository = "https://github.com/yazaldefilimone/dunh"
license = "MIT"
keywords = ["console", "terminal", "error"]
categories = ["compilers", "text-processing"]

[dependencies]
